import type { CommonMistake, DayNumber, Lesson, QuizQuestion } from '../types';

export const dayMeta: Record<DayNumber, { title: string; subtitle: string; color: string }> = {
  1: { title: 'Foundations', subtitle: 'The UI mental model', color: 'coral' },
  2: { title: 'State & interaction', subtitle: 'Make the interface respond', color: 'mint' },
  3: { title: 'Effects & APIs', subtitle: 'Connect to the outside world', color: 'gold' },
  4: { title: 'Reusable logic', subtitle: 'Compose production patterns', color: 'violet' },
  5: { title: 'Production React', subtitle: 'Read, trace, and debug a repo', color: 'blue' },
};

const q = (id: string, prompt: string, options: string[], answer: number, explanation: string, code?: string) => ({ id, prompt, options, answer, explanation, code });

const quizExpansions: Record<string, QuizQuestion[]> = {
  jsx: [
    q('jsx-2', 'What value does this render?', ['Hello undefined', 'Hello Harish', 'The literal text {name}', 'Nothing'], 1, 'The braces evaluate the name variable during render, so React receives the text Hello Harish.', `const name = 'Harish';\n<h2>Hello {name}</h2>`),
    q('jsx-3', 'What is wrong with putting an if statement directly inside JSX braces?', ['JSX cannot use variables', 'if is a statement, not an expression', 'React forbids conditions', 'The browser cannot parse h2'], 1, 'JSX braces expect an expression that produces a value. Put if outside the return or use a ternary for two inline choices.'),
  ],
  components: [
    q('components-2', 'What does React do first when CustomerPage needs to update?', ['It reloads the browser document', 'It calls CustomerPage to calculate new JSX', 'It calls the database', 'It changes CSS only'], 1, 'React executes the component again, then compares the returned UI description with the previous one.'),
    q('components-3', 'Which return value is a useful component boundary?', ['A JSX description of one UI responsibility', 'A direct SQL query', 'A CSS file path only', 'A mutable DOM node'], 0, 'A component is a function that returns UI description and can compose smaller components.'),
  ],
  props: [
    q('props-2', 'A parent changes name from Maya to Asha. What happens next?', ['The child keeps mutating Maya', 'The child receives new props and renders Asha', 'Only the database changes', 'The browser reloads'], 1, 'The parent owns the value. Its next render passes the new prop, so the child calculates UI from Asha.'),
    q('props-3', 'What should a child do when it needs a different value?', ['Assign directly to props', 'Ask the parent through a callback', 'Change the DOM behind React', 'Write to localStorage only'], 1, 'Props are read-only inputs. A callback lets the child communicate an event while the parent remains the owner.'),
  ],
  rendering: [
    q('render-2', 'A component calls setCount(count + 1). What causes the function to run again?', ['The setter schedules a state update', 'The return statement loops', 'The browser reloads', 'console.log'], 0, 'The setter tells React its state changed. React schedules another render and executes the component again.'),
    q('render-3', 'What does a re-render NOT mean?', ['Component JavaScript runs again', 'React calculates fresh JSX', 'The whole browser page reloads', 'React may commit DOM changes'], 2, 'A re-render is React recalculating UI. It is not a full document navigation or browser reload.'),
  ],
  'use-state': [
    q('state-2', 'What will two direct updates do in one click?', ['Always add two', 'Usually add one because both read the same snapshot', 'Reset to zero', 'Throw a Promise'], 1, 'Both count + 1 expressions read the same render snapshot. Functional updates are needed to compose increments.'),
    q('state-3', 'What is the purpose of setCount(value => value + 1)?', ['Read the latest queued state', 'Mutate the DOM directly', 'Skip rendering', 'Create a prop'], 0, 'The updater function receives the latest state value, so multiple queued updates can build on one another.', `setCount(value => value + 1);\nsetCount(value => value + 1);`),
    q('state-4', 'Why does useState(null) not erase a customer on every render?', ['React ignores null', 'The argument is only the initial value for that state slot', 'null means loading forever', 'Hooks run only once'], 1, 'After the state slot exists, React returns its current memory value. The argument is not a reset command.'),
  ],
  events: [
    q('events-2', 'A click handler reads count = 0 and calls setCount(1). What does the next UI show?', ['0 forever', '1 after React renders again', 'undefined', 'A new browser tab'], 1, 'The event schedules a state update. The next render reads count as 1 and produces the new button text.'),
    q('events-3', 'Why does a form use preventDefault in onSubmit?', ['To stop React state', 'To stop the browser navigation and keep the flow in React', 'To call fetch automatically', 'To create a key'], 1, 'The browser’s default form navigation would replace the page. preventDefault lets the handler manage submission.'),
  ],
  'lists-and-keys': [
    q('keys-2', 'A new user is inserted at index 0. Why can index keys be risky?', ['Indexes are never numbers', 'Existing component state can be matched to the wrong user', 'map stops working', 'Keys are visible text'], 1, 'Index keys describe position, not identity. Inserting at the front shifts positions and can move state between rows.'),
    q('keys-3', 'What should a key remain stable across?', ['Only one render', 'Reorders and list updates for the same logical item', 'Only server restarts', 'CSS changes'], 1, 'A stable domain id lets React recognize the same logical item across renders.'),
  ],
  forms: [
    q('forms-2', 'The input value is stored in React state. What happens after typing?', ['onChange updates state, then value reflects the next render', 'The database paints the input', 'React ignores the keystroke', 'The page must reload'], 0, 'A controlled input reports the browser event and receives the current state value back from React.'),
    q('forms-3', 'What is a common warning sign of a controlled/uncontrolled mix?', ['The input changes theme', 'An input switches between missing value and defined value', 'A list gains a key', 'A route gets a parameter'], 1, 'Changing between undefined and a defined value means ownership of the input value is changing during its lifetime.'),
  ],
  effects: [
    q('effects-2', 'What is the order for an effect-driven request?', ['Effect → render → commit', 'Render → commit → effect', 'Commit → database → render only', 'JSX → browser reload → effect'], 1, 'React renders and commits the UI first. Then the effect synchronizes with the external system.'),
    q('effects-3', 'Why should cleanup unsubscribe from an external system?', ['To make JSX shorter', 'To stop old subscriptions from continuing after the component changes or unmounts', 'To reset all state', 'To create props'], 1, 'Cleanup prevents stale listeners, timers, or requests from affecting a screen that no longer owns them.'),
  ],
  'dependency-arrays': [
    q('deps-2', 'If userId changes from 101 to 102, what happens with [userId]?', ['No effect ever runs', 'Cleanup for the old effect can run, then the effect runs for 102', 'Only the DOM changes', 'The route disappears'], 1, 'React compares the dependency. A changed value causes the previous effect to be cleaned up before the new setup runs.'),
    q('deps-3', 'What is the risk of an empty dependency array around code that reads userId?', ['It runs on every keystroke', 'It can keep using the initial userId when the value later changes', 'It prevents the first effect', 'It makes userId global'], 1, 'An empty array says the effect does not depend on changing values. Reading a changing userId there can create a stale closure.'),
  ],
  'promises-and-async': [
    q('promise-2', 'What does await do inside an async function?', ['It turns the Promise into a synchronous database call', 'It pauses that async function until the Promise settles', 'It reloads the browser', 'It changes JSX directly'], 1, 'await makes the success path read top-to-bottom while the underlying Promise remains asynchronous.'),
    q('promise-3', 'Where should a rejected API Promise be handled?', ['Only in CSS', 'In catch or try/catch, then update error state', 'Inside a key prop', 'Never'], 1, 'Handling rejection lets the UI explain failure instead of leaving the user with an untracked pending state.'),
  ],
  'api-flow': [
    q('api-2', 'What does the user see before the customer response arrives?', ['The customer name from the future', 'The loading branch based on initial state', 'A database screen', 'Nothing because effects block render'], 1, 'The first render uses customer = null, so the UI renders Loading before the effect’s request completes.'),
    q('api-3', 'A response is 200 but the name is blank. What should you compare first?', ['Only the CSS', 'The response shape and the property JSX reads', 'The browser wallpaper', 'The route color'], 1, 'A successful HTTP status does not guarantee the property path matches. Compare the payload with customer.name.'),
  ],
  'custom-hooks': [
    q('hook-2', 'What belongs in a service rather than useUsers?', ['setLoading state', 'The HTTP URL and request details', 'A component return', 'A Hook call'], 1, 'The service owns integration details. The Hook coordinates React state, effects, and the result exposed to the page.'),
    q('hook-3', 'Why can two pages call the same custom Hook?', ['Hooks copy the DOM', 'The Hook packages reusable stateful behavior', 'The database shares components', 'Props become global'], 1, 'Each component gets its own Hook state while sharing the same logic shape.'),
  ],
  context: [
    q('context-2', 'What happens when a consumer is under a Provider with a new value?', ['Only the provider’s CSS changes', 'The consumer reads the new context value and may render again', 'The route is removed', 'The database is updated automatically'], 1, 'Context is an input to the consumer. A changed provider value can update consumers that read it.'),
    q('context-3', 'When is Context a poor fit?', ['For a theme used across the app', 'For every tiny local input value', 'For current authenticated user', 'For locale'], 1, 'Local state should remain local. Context is most useful for values shared across distant parts of a tree.'),
  ],
  refs: [
    q('ref-2', 'After inputRef.current changes, what normally happens?', ['React renders automatically', 'The ref stores the new value without scheduling a render', 'The route changes', 'The input becomes state'], 1, 'Refs are mutable storage. Use state when the new value needs to appear in the UI.'),
    q('ref-3', 'Why is focus a good useRef example?', ['Focus is an imperative DOM action', 'Focus is a database query', 'Refs replace all state', 'The DOM cannot be rendered'], 0, 'React describes the input declaratively, while the click handler uses the ref for one imperative focus action.'),
  ],
  memoization: [
    q('memo-2', 'When does useMemo recalculate this value?', ['Every browser paint', 'When a dependency changes', 'Only after a fetch', 'Never'], 1, 'React can reuse the memoized value while its dependency list remains equal.'),
    q('memo-3', 'Why might useCallback matter to a memoized child?', ['It changes the function’s behavior into CSS', 'It can preserve function identity when dependencies are unchanged', 'It prevents all renders', 'It makes functions global'], 1, 'A memoized child can compare the callback reference. useCallback can keep that reference stable when appropriate.'),
  ],
  routing: [
    q('route-2', 'What does /customers/:id capture for /customers/101?', ['The entire database', 'The route parameter id = 101', 'A CSS variable', 'The component name'], 1, 'The dynamic segment captures 101 and makes it available to the matched page.'),
    q('route-3', 'Why are real routes useful in a production app?', ['They make every component global', 'They make screens addressable, navigable, and refreshable by URL', 'They remove state', 'They replace APIs'], 1, 'A route is a stable navigation contract between the URL and a page component.'),
  ],
  debugging: [
    q('debug-2', 'The route is correct but no request appears in Network. What should you inspect next?', ['The database schema first', 'Whether the page rendered and the effect/request code ran', 'Only button color', 'React version in CSS'], 1, 'The trace is ordered. If Network is empty, confirm the component and effect reached the request boundary.'),
    q('debug-3', 'The response has data and setCustomer runs, but UI stays blank. What is the next check?', ['Whether JSX reads the correct property', 'Whether the keyboard is plugged in', 'Whether the route is uppercase', 'Whether CSS has a key'], 0, 'After state updates, compare the property path JSX reads with the actual response shape.'),
  ],
};

const commonMistakes: Record<string, CommonMistake> = {
  props: { title: 'Mutating a prop in the child', wrongCode: `function User({ name }) {\n  name = 'Asha';\n  return <h2>{name}</h2>;\n}`, why: 'The child does not own the parent’s input. A local reassignment cannot update the parent or other consumers.', correctCode: `function User({ name, onRename }) {\n  return <button onClick={onRename}>{name}</button>;\n}`, works: 'The child reports an event and the parent decides the next prop value.' },
  'use-state': { title: 'Treating state like a normal variable', wrongCode: `count = count + 1;\n// UI does not know about this`, why: 'A local assignment does not tell React to render again.', correctCode: `setCount(value => value + 1);`, works: 'The setter updates React’s state memory and schedules a render with the latest value.' },
  'state-ownership': { title: 'Mutating an array in state', wrongCode: `users.push(newUser);\nsetUsers(users);`, why: 'The existing array reference was changed in place. That makes ownership and change detection harder to reason about.', correctCode: `setUsers(items => [...items, newUser]);`, works: 'A new array describes the next state clearly and keeps the previous snapshot untouched.' },
  events: { title: 'Using a stale event snapshot', wrongCode: `setCount(count + 1);\nsetCount(count + 1);`, why: 'Both expressions read count from the same render snapshot, so they request the same next value.', correctCode: `setCount(value => value + 1);\nsetCount(value => value + 1);`, works: 'Functional updates receive the latest queued state and compose safely.' },
  'lists-and-keys': { title: 'Using the array index as identity', wrongCode: `users.map((user, index) => (\n  <Row key={index} user={user} />\n))`, why: 'Insertions and reorders change indexes, so React can attach one row’s state to another user.', correctCode: `users.map(user => (\n  <Row key={user.id} user={user} />\n))`, works: 'A stable domain id follows the logical item across list changes.' },
  forms: { title: 'Mixing controlled and uncontrolled input', wrongCode: `<input value={name} />\n// no onChange`, why: 'React owns the value but the user has no update path, so the field becomes read-only.', correctCode: `<input value={name}\n  onChange={event => setName(event.target.value)} />`, works: 'The browser reports the edit and React sends the current state back as the value.' },
  effects: { title: 'Starting an API call during render', wrongCode: `function Page() {\n  fetch('/api/customers');\n  return <Loading />;\n}`, why: 'Render should be a predictable calculation. A request during render can repeat whenever React calculates UI.', correctCode: `useEffect(() => {\n  fetch('/api/customers');\n}, []);`, works: 'The effect starts the external side effect after React commits the initial UI.' },
  'dependency-arrays': { title: 'Ignoring the value an effect reads', wrongCode: `useEffect(() => {\n  loadUser(userId);\n}, []);`, why: 'The empty array freezes the initial userId in the effect’s closure.', correctCode: `useEffect(() => {\n  loadUser(userId);\n}, [userId]);`, works: 'The dependency tells React to clean up and rerun when the userId changes.' },
  'promises-and-async': { title: 'Leaving a rejected Promise unhandled', wrongCode: `fetch(url)\n  .then(showData);\n// no catch`, why: 'A network or parsing failure has no path to error state, so the UI can stay misleadingly pending.', correctCode: `try {\n  const data = await load(url);\n  setData(data);\n} catch {\n  setError('Request failed');\n}`, works: 'Every asynchronous path becomes visible UI state.' },
  'custom-hooks': { title: 'Calling a Hook conditionally', wrongCode: `if (loggedIn) {\n  useUsers();\n}`, why: 'Changing Hook order prevents React from matching state slots consistently between renders.', correctCode: `const users = useUsers();\nif (!loggedIn) return <Login />;`, works: 'Hooks run in the same order; conditions decide what UI to return.' },
  'rules-of-hooks': { title: 'Calling a Hook inside a condition', wrongCode: `if (condition) {\n  useState(0);\n}`, why: 'React identifies Hook state by call order. A condition can make the order change between renders.', correctCode: `const [count, setCount] = useState(0);\nif (!condition) return null;`, works: 'The Hook is always called; the condition only chooses the rendered result.' },
  context: { title: 'Putting all state in Context', wrongCode: `<AppContext.Provider value={{ everyInput }}>`, why: 'Globalizing local state makes updates and ownership harder to trace.', correctCode: `<ThemeProvider value={theme}>\n  <App />\n</ThemeProvider>`, works: 'Context is reserved for values many distant consumers genuinely share.' },
  refs: { title: 'Using a ref for visible UI state', wrongCode: `countRef.current += 1;\n// screen does not update`, why: 'Changing ref.current does not schedule a render.', correctCode: `const [count, setCount] = useState(0);\nsetCount(value => value + 1);`, works: 'State is the tool for values the UI must display.' },
  memoization: { title: 'Memoizing everything', wrongCode: `const value = useMemo(() => name, [name]);`, why: 'Memoization adds complexity and has a cost. It does not improve a trivial calculation.', correctCode: `const result = useMemo(\n  () => expensiveCalculation(data),\n  [data]\n);`, works: 'Use memoization when an expensive calculation or identity boundary justifies it.' },
  'api-flow': { title: 'Only modeling the success state', wrongCode: `return <h1>{customer.name}</h1>;`, why: 'The first render has no customer yet, and a failed request has no customer either.', correctCode: `if (loading) return <Loading />;\nif (error) return <ErrorMessage />;\nreturn <h1>{customer?.name}</h1>;`, works: 'Explicit loading, error, and success branches match the real request lifecycle.' },
  debugging: { title: 'Jumping straight to CSS', wrongCode: `// customer name is blank\n// change text color first`, why: 'A visual symptom may come from route, request, response, state, or JSX. Styling is late in the execution chain.', correctCode: `route → render → request → response\n→ setState → JSX property`, works: 'A fixed execution order narrows the root cause quickly.' },
};

const lesson = (id: string, day: DayNumber, title: string, description: string, sections: Lesson['sections'], quiz: Lesson['quiz'], tags: string[], challenge?: Lesson['challenge']): Lesson => ({
  id, day, title, slug: id, description, sections, quiz: [...quiz, ...(quizExpansions[id] ?? [])], tags, challenge, commonMistake: commonMistakes[id], estimatedMinutes: Math.max(12, sections.length * 5), prerequisites: [],
});

export const lessons: Lesson[] = [
  lesson('javascript-foundations', 1, 'JavaScript foundations', 'The small set of JavaScript ideas that React code uses constantly.', [
    { title: 'Start with the familiar', body: 'You already know variables, objects, collections, and methods from Java. JavaScript has the same building blocks, but functions are values and objects are often assembled inline.', code: `const customer = { name: 'Harish', active: true };\nconst label = customer.active ? customer.name : 'Inactive';`, takeaway: 'React is JavaScript first. JSX and Hooks become much easier once these expressions feel normal.' },
    { title: 'Why map appears everywhere', body: 'A component often turns an array of data into an array of UI. map returns a new array; it does not mutate the original collection.', code: `const names = ['Asha', 'Maya'];\nconst items = names.map(name => <li key={name}>{name}</li>);` },
    { title: 'The async bridge', body: 'fetch returns a Promise. async/await lets you read the same asynchronous flow from top to bottom, while React state gives the result somewhere visible to render.', code: `async function loadCustomer() {\n  const response = await fetch('/api/customers/101');\n  return response.json();\n}` },
  ], [q('js-1', 'What does map return?', ['The original array with hidden changes', 'A new array containing each transformed item', 'A Promise', 'Only the last item'], 1, 'map creates a new array. That is why React can use it to produce a list of elements without changing the source data.')], ['javascript', 'map', 'async'], { title: 'Translate a backend response', prompt: 'Create a small object with name and status, then derive a display label using a ternary expression.', hints: ['Start with const customer = ...', 'Use customer.status in the condition.'] }),
  lesson('jsx', 1, 'JSX: describe the UI', 'JSX looks like HTML, but it is JavaScript syntax for describing what React should create.', [
    { title: 'JSX is a description', body: 'When you write <h1>Hello</h1>, React receives a description of an h1 element. It is not a string of HTML and the browser does not execute it directly.', code: `const element = <h1>Hello, {name}</h1>;\n// conceptually becomes React.createElement(...)`, takeaway: 'Curly braces are the bridge from markup-shaped JSX into JavaScript expressions.' },
    { title: 'A useful translation', body: 'The JSX compiler turns nested tags into nested element descriptions. React can then compare the new description with the previous one and update only what needs to change.', code: `const element = React.createElement('h1', null, 'Hello');` },
  ], [q('jsx-1', 'What can go inside JSX curly braces?', ['A JavaScript expression', 'A complete if statement', 'A CSS selector only', 'A backend request'], 0, 'Curly braces evaluate an expression such as a variable, ternary, function call, or mapped array. Statements like if are written outside JSX.')], ['jsx', 'syntax'], { title: 'Make a greeting', prompt: 'Use the playground to change the name and observe the live JSX output.', hints: ['The value between the braces is evaluated during render.'] }),
  lesson('components', 1, 'Components', 'A component is a function that returns a description of one part of the interface.', [
    { title: 'The function is the unit', body: 'React calls your component function to find out what should be on screen. A component can combine other components, values, and event handlers into a meaningful UI boundary.', code: `function CustomerPage() {\n  return <h1>Customers</h1>;\n}` },
    { title: 'What happens when it runs', body: 'The browser does not call CustomerPage. React does. React receives the returned JSX, commits the result to the DOM, and the browser paints the pixels.', takeaway: 'Think: component function → UI description → React commit → browser pixels.' },
  ], [q('component-1', 'Who executes a component function?', ['The database', 'The browser HTML parser', 'React during rendering', 'The CSS engine'], 2, 'React executes the function to calculate the UI description. The browser receives DOM changes after React commits them.')], ['components', 'rendering'], { title: 'Build a status component', prompt: 'Change the returned JSX so the component shows a customer name and an active badge.', hints: ['A component can return a fragment with multiple elements.', 'Keep the returned value as JSX.'] }),
  lesson('props', 1, 'Props and children', 'Props are read-only inputs flowing from a parent component into a child.', [
    { title: 'Data flows down', body: 'The parent chooses the value. The child reads it while rendering. This is similar to passing method parameters, except React uses the values to describe UI.', code: `function User({ name }: { name: string }) {\n  return <h2>{name}</h2>;\n}\n\n<User name="Harish" />;` },
    { title: 'Children are a slot', body: 'The children prop lets a component wrap arbitrary JSX. A child should not mutate its props; the parent owns the input and can render a new value later.', code: `function Card({ children }: { children: React.ReactNode }) {\n  return <section className="card">{children}</section>;\n}` },
  ], [q('props-1', 'Where does the name value come from?', ['The child changes its own prop', 'The parent passes it to User', 'The DOM invents it', 'The API always owns it'], 1, 'The parent passes name="Harish". The child receives a read-only snapshot for that render.')], ['props', 'composition'], { title: 'Pass multiple props', prompt: 'Use the interactive parent and child preview to change the name, role, and status.', hints: ['Each prop is an attribute on the component.', 'The child renders the values it receives.'] }),
  lesson('rendering', 1, 'Rendering and re-rendering', 'Rendering means React runs components again to calculate what the UI should be now. It is not a full page reload.', [
    { title: 'The render loop', body: 'A state update schedules another render. React executes the component, gets fresh JSX, compares it with the previous result, and commits the necessary DOM changes.', code: `CustomerPage()\n  ↓\nJSX returned\n  ↓\nReact compares UI descriptions\n  ↓\nDOM updates`, takeaway: 'A re-render is JavaScript execution, not a browser navigation.' },
    { title: 'Watch it happen', body: 'The demo on this lesson increments a render count using actual React state. Trigger the update and watch the function execution event appear in order.', code: `const [renderCount, setRenderCount] = useState(1);\nsetRenderCount(count => count + 1);` },
  ], [q('render-1', 'What usually causes a component to render again?', ['console.log()', 'A state update or new parent input', 'A CSS color', 'The return keyword by itself'], 1, 'State updates and changed props/context schedule React to calculate the component again. Logging alone has no UI effect.')], ['rendering', 'mental-model']),
  lesson('entry-point', 1, 'The React entry point', 'See how a browser element becomes the root of a React application.', [
    { title: 'The handoff', body: 'The browser starts with a plain div. ReactDOM.createRoot attaches React to that node, then the App component becomes the top of the component tree.', code: `const root = document.getElementById('root');\ncreateRoot(root!).render(<App />);` },
  ], [q('entry-1', 'What does createRoot connect to?', ['A database table', 'The root DOM element', 'A CSS file', 'A Promise'], 1, 'createRoot takes the DOM node where React is allowed to manage the application UI.')], ['entry-point', 'architecture']),

  lesson('use-state', 2, 'useState and state memory', 'State is React-owned memory that lets a component remember values between renders.', [
    { title: 'Initial value versus current value', body: 'useState(0) supplies the initial value when React creates this state slot. On later renders React returns the current value from its memory; it does not reset it to zero.', code: `const [count, setCount] = useState(0);\n\nsetCount(count + 1);`, takeaway: 'The setter asks React for another render with new state.' },
    { title: 'State is not a normal variable', body: 'Assigning count = count + 1 would only change a local variable. setCount communicates with React, schedules work, and makes the new value available on the next render.' },
  ], [q('state-1', 'What does useState(0) mean on render two?', ['Reset count to zero', 'Retrieve the existing state slot', 'Create a database row', 'Run an effect'], 1, 'The argument is used when the state is created. Later renders retrieve the existing value.')], ['state', 'hooks'], { title: 'Make a counter', prompt: 'Use +1, -1, and Reset to observe state memory and the render timeline.', hints: ['Each setter call schedules a real React update.', 'The UI reads the current count during render.'] }),
  lesson('events', 2, 'Events and updates', 'User events enter React through handlers, which can update state and cause a re-render.', [
    { title: 'The event flow', body: 'A click is delivered to the handler. The handler calls a setter. React updates its state memory and runs the component again. The new JSX contains the visible change.', code: `<button onClick={() => setCount(count + 1)}>Increment</button>` },
    { title: 'Form events', body: 'Inputs use onChange to move the browser value into React state. onSubmit handles the form-level action and can prevent a page navigation.', code: `<input value={name} onChange={event => setName(event.target.value)} />` },
  ], [q('events-1', 'What should an onClick handler do to change visible state?', ['Mutate the DOM directly', 'Call a state setter', 'Only print to the console', 'Reload the page'], 1, 'Calling the setter gives React the information it needs to update state and render the new UI.')], ['events', 'forms']),
  lesson('conditional-rendering', 2, 'Conditional rendering', 'Use normal JavaScript conditions to choose which UI description React should receive.', [
    { title: 'Choose a branch', body: 'A ternary is useful when there are two visible alternatives. The && pattern is useful when a block should appear only when a condition is true.', code: `{loading ? <Spinner /> : <CustomerCard />}` },
    { title: 'Loading is a state', body: 'A loading label is not an animation pretending that work happened. It is a direct reflection of the current request state and changes when that state changes.' },
  ], [q('conditional-1', 'What does a ternary choose?', ['Two possible expressions', 'A CSS animation duration', 'A database query', 'A component file'], 0, 'condition ? A : B evaluates either A or B, which makes it a compact way to describe alternate UI.')], ['conditions', 'loading']),
  lesson('lists-and-keys', 2, 'Lists and keys', 'Turn collections into UI while giving React stable identity for each item.', [
    { title: 'map makes elements', body: 'Map transforms each data item into an element. key is not displayed to the user; it helps React match old and new items when the collection changes.', code: `users.map(user => (\n  <UserRow key={user.id} user={user} />\n))` },
    { title: 'Why index can be risky', body: 'If items are inserted or reordered, an index key can make React associate old state with the wrong person. Stable domain IDs preserve identity.', takeaway: 'Keys describe identity, not position.' },
  ], [q('keys-1', 'What is the best key for a dynamic customer list?', ['The array index', 'A stable customer id', 'The current time on every render', 'The customer object itself'], 1, 'A stable id lets React match the same logical customer even when the list changes order.')], ['lists', 'keys']),
  lesson('forms', 2, 'Controlled forms', 'Keep an input value in React state so the screen and the data model stay synchronized.', [
    { title: 'The controlled loop', body: 'The browser emits onChange. React stores the new value. The next render gives that value back to the input through value. This creates one clear source of truth.', code: `const [name, setName] = useState('');\n<input value={name} onChange={e => setName(e.target.value)} />` },
  ], [q('forms-1', 'In a controlled input, where does the displayed value come from?', ['Only the DOM', 'React state passed to value', 'The database directly', 'The submit button'], 1, 'React state is the source of truth. The input reports changes and receives the current value back.')], ['forms', 'controlled']),
  lesson('state-ownership', 2, 'Immutability and state ownership', 'Decide which component owns a value and update arrays/objects by creating new references.', [
    { title: 'Lift state to the owner', body: 'If two sibling components need the same value, move that state to their closest shared parent and pass the value and callbacks down.', code: `function App() {\n  const [query, setQuery] = useState('');\n  return <><Search value={query} onChange={setQuery} /><Results query={query} /></>;\n}` },
    { title: 'Create the next collection', body: 'Use map, filter, or spread to describe a new collection. Do not mutate the existing state array in place.', code: `setUsers(users => users.filter(user => user.id !== id));` },
  ], [q('ownership-1', 'Where should shared sibling state usually live?', ['Inside whichever child renders first', 'In their closest shared parent', 'In the DOM', 'Inside a random utility'], 1, 'The shared parent can own the value and pass it to each child, keeping one source of truth.')], ['state', 'immutability', 'lifting']),

  lesson('effects', 3, 'Render, commit, and effects', 'Use effects to synchronize React with systems outside the render calculation.', [
    { title: 'Render is a calculation', body: 'Render should be predictable: read props/state and return JSX. After React commits the DOM, an effect can start a timer, request, subscription, or other external synchronization.', code: `useEffect(() => {\n  document.title = 'Customers';\n}, []);` },
    { title: 'The dependency story', body: 'No array runs after every commit. [] runs after the initial mount. [userId] runs after mount and when userId changes. React compares dependency values between commits.', takeaway: 'Dependencies describe which render values the effect reads.' },
  ], [q('effects-1', 'When should an API request usually start?', ['During render', 'After commit inside an effect', 'Inside a JSX string', 'Only after a full page reload'], 1, 'An API request is a side effect. Starting it after commit keeps rendering a pure calculation.')], ['effects', 'useEffect', 'render', 'commit']),
  lesson('dependency-arrays', 3, 'Dependency arrays', 'Predict exactly when an effect runs and why Strict Mode can make development behavior look different.', [
    { title: 'Three cases', body: 'An effect with no dependency array runs after every commit. An empty array runs after mount. A dependency array runs when one of its listed values changes.', code: `useEffect(runEveryCommit);\nuseEffect(runOnceAfterMount, []);\nuseEffect(runWhenUserChanges, [userId]);` },
    { title: 'Development clarity', body: 'Strict Mode may intentionally replay setup in development to reveal unsafe effects. It does not mean production sends every request twice. Cleanup should make setup safe to repeat.' },
  ], [q('deps-1', 'If userId stays 101 during a re-render, will [userId] rerun?', ['Yes, every render', 'No, the dependency value did not change', 'Only if JSX has a button', 'Only in production'], 1, 'React compares the dependency value. A re-render alone does not rerun an effect when userId is still 101.')], ['effects', 'useEffect', 'dependencies']),
  lesson('promises-and-async', 3, 'Promises and async/await', 'Follow asynchronous work from pending to fulfilled or rejected.', [
    { title: 'A Promise is a future result', body: 'fetch returns immediately with a Promise. The Promise starts pending, then becomes fulfilled with a response or rejected with an error. .then and .catch register what to do next.', code: `fetch('/api/customers/101')\n  .then(response => response.json())\n  .then(data => setCustomer(data))\n  .catch(error => setError(error));` },
    { title: 'The readable version', body: 'async/await is syntax over the same Promise behavior. try/catch makes the success and error paths visually obvious. It is conceptually similar to CompletableFuture composition, but it is JavaScript behavior.', code: `try {\n  const response = await fetch(url);\n  const data = await response.json();\n} catch (error) {\n  setError(error);\n}` },
  ], [q('promise-1', 'What is the first state of a fetch Promise?', ['Fulfilled', 'Pending', 'Rendered', 'Mounted'], 1, 'The request begins pending. It later fulfills or rejects, and your code updates UI state for the result.')], ['promises', 'async', 'errors']),
  lesson('api-flow', 3, 'The complete API flow', 'Trace a customer request from initial render through HTTP response and the second render.', [
    { title: 'One request, two renders', body: 'The first render shows Loading. After commit, useEffect starts fetch. When data arrives, setCustomer updates React state and the component executes again. The second render reads the customer.', code: `const [customer, setCustomer] = useState<Customer | null>(null);\n\nuseEffect(() => {\n  fetch('/api/customers/101')\n    .then(response => response.json())\n    .then(setCustomer);\n}, []);` },
    { title: 'Production states', body: 'A useful API screen makes loading, success, error, and empty data explicit. These are different states, not one generic fallback.', takeaway: 'The UI should make the network lifecycle observable.' },
  ], [q('api-1', 'What causes CustomerPage to show Harish after the response?', ['fetch changes the DOM directly', 'setCustomer updates state and schedules a render', 'The database paints pixels', 'The effect returns JSX'], 1, 'The response callback calls setCustomer. React stores the data, runs the component again, and the new JSX reads customer.name.')], ['api', 'loading', 'errors'], { title: 'Trace the request', prompt: 'Run the API simulator in success, error, empty, and slow modes. Step through the request lifecycle.', hints: ['Start at the initial loading state.', 'Notice where setCustomer or setError enters the flow.'] }),

  lesson('custom-hooks', 4, 'Custom Hooks', 'Package reusable React-specific state and effects behind a function beginning with use.', [
    { title: 'A Hook is a logic boundary', body: 'useUsers can own loading, users, and the effect that loads them. A page consumes the returned result without duplicating the lifecycle code.', code: `function useUsers() {\n  const [users, setUsers] = useState([]);\n  const [loading, setLoading] = useState(true);\n  useEffect(() => { getUsers().then(setUsers).finally(() => setLoading(false)); }, []);\n  return { users, loading };\n}` },
    { title: 'Hook versus service', body: 'The Hook knows React state and effects. The service knows how to communicate with the API. Keeping those responsibilities separate makes a repository easier to trace and test.' },
  ], [q('hook-1', 'What makes useUsers a custom Hook?', ['It returns JSX', 'It combines reusable React Hook logic', 'It is stored in a database', 'It must be a class'], 1, 'A custom Hook is a function that uses React Hooks to share stateful behavior between components.')], ['hooks', 'architecture']),
  lesson('context', 4, 'Context and providers', 'Share values across a component tree when prop passing would become noisy.', [
    { title: 'The provider boundary', body: 'A Provider makes a value available to descendants. A component can read it with useContext without every intermediate component receiving a prop just to pass it along.', code: `<AuthProvider>\n  <App />\n</AuthProvider>\n\nconst { user } = useContext(AuthContext);` },
    { title: 'Use it intentionally', body: 'Context is useful for app-wide concerns such as the current user, theme, or locale. It is not a reason to put every piece of local state in a global container.' },
  ], [q('context-1', 'What problem does Context reduce?', ['All network latency', 'Prop drilling through unrelated layers', 'The need for components', 'Every re-render'], 1, 'Context lets a descendant read a shared value without passing it through every intermediate component.')], ['context', 'provider']),
  lesson('refs', 4, 'useRef and the DOM', 'Keep a mutable reference to a DOM node or value without scheduling a render.', [
    { title: 'Imperative escape hatch', body: 'A ref can point to an input. A click handler can read inputRef.current and call focus. React still renders the input; the ref gives you a direct handle for a focused imperative action.', code: `const inputRef = useRef<HTMLInputElement>(null);\n<input ref={inputRef} />\n<button onClick={() => inputRef.current?.focus()}>Focus</button>` },
    { title: 'Changing current is not a render trigger', body: 'Updating ref.current changes the stored reference, but React does not re-run the component just because the ref changed. Use state when the value should appear in UI.' },
  ], [q('ref-1', 'Does changing ref.current normally re-render?', ['Yes, always', 'No, refs do not schedule renders', 'Only when a Promise fulfills', 'Only in CSS'], 1, 'Refs are mutable storage for values or DOM handles. State is the tool for values that should update visible UI.')], ['refs', 'dom']),
  lesson('memoization', 4, 'useMemo and useCallback', 'Cache a calculation or function reference only when identity or repeated work matters.', [
    { title: 'useMemo caches a value', body: 'useMemo can reuse an expensive calculation until its dependencies change. It is an optimization, not a replacement for correct state flow.', code: `const result = useMemo(() => expensiveCalculation(data), [data]);` },
    { title: 'useCallback caches a function', body: 'A new function is created during each render. useCallback can preserve the reference when a memoized child cares about identity. Do not add it everywhere by reflex.', code: `const onSelect = useCallback((id: number) => setSelectedId(id), []);` },
  ], [q('memo-1', 'When should useMemo be considered?', ['For every variable', 'When a calculation is expensive or identity matters', 'To make an API request', 'To replace useState'], 1, 'Memoization has a cost. Use it when measurement or a known identity boundary makes the tradeoff useful.')], ['memo', 'performance']),
  lesson('rules-of-hooks', 4, 'Rules of Hooks', 'Keep Hook calls at stable positions so React can match state slots across renders.', [
    { title: 'The stable order rule', body: 'Call Hooks at the top level of a component or custom Hook. Do not call them inside conditions, loops, or nested functions. React associates each call by order.', code: `function Component() {\n  const [count, setCount] = useState(0);\n  return <button onClick={() => setCount(count + 1)}>{count}</button>;\n}` },
    { title: 'The tempting mistake', body: 'If a Hook runs only when loggedIn is true, the next render can shift every later state slot. The rules make Hook order predictable.', code: `// Bad\nif (loggedIn) {\n  useState(null);\n}` },
  ], [q('hooks-rules-1', 'Where may a Hook be called?', ['Inside a conditional', 'At the top level of a component or custom Hook', 'Inside a map callback', 'Inside a click handler'], 1, 'Stable top-level calls preserve the order React uses to associate state and effects with the right component.')], ['hooks', 'rules']),

  lesson('routing', 5, 'Routing and URLs', 'Let the URL select the page and route parameters carry resource identity.', [
    { title: 'The route contract', body: 'A route maps a URL pattern to a page component. /customers/101 matches /customers/:id, and the page can read id to load the right customer.', code: `<Route path="/customers/:id" element={<CustomerDetailsPage />} />` },
    { title: 'Why this matters', body: 'Real repositories use routes to make screens bookmarkable, refreshable, and connected to navigation history. A route is part of the app’s public interface.' },
  ], [q('route-1', 'Which route matches /customers/101?', ['/customers', '/customers/:id', '/users/:name/edit', '/'], 1, 'The :id segment captures 101 as a route parameter for the customer details page.')], ['routing', 'urls']),
  lesson('repository-structure', 5, 'Navigate a React repository', 'Learn how pages, components, hooks, services, context, and routes fit together.', [
    { title: 'A useful first pass', body: 'Start at main.jsx, then App, then routes. Follow the selected page to its components, Hook, and service. This is the frontend version of tracing Controller → Service → Repository in Spring.', code: `src/\n├── main.jsx\n├── App.jsx\n├── pages/\n├── components/\n├── hooks/\n├── services/\n├── context/\n└── routes/` },
    { title: 'Read the data path', body: 'A page usually owns composition, a Hook owns React lifecycle logic, and a service owns HTTP details. The browser and backend stay connected through a sequence of explicit boundaries.' },
  ], [q('repo-1', 'Where should an HTTP URL usually live?', ['Inside every button JSX', 'In a service/integration layer', 'Inside CSS', 'Only in the router'], 1, 'A service centralizes API communication so pages and Hooks can focus on UI and lifecycle behavior.')], ['architecture', 'repository']),
  lesson('debugging', 5, 'Debugging a missing customer', 'Use a systematic trace instead of guessing when data is not appearing.', [
    { title: 'Ask in execution order', body: 'Check the route, component render, request, status, response shape, state update, re-render, and JSX property. Each question narrows the fault location.', code: `route → render → request → status → response → setState → render → JSX` },
    { title: 'Use the right panel', body: 'Elements answers what is in the DOM. Network answers what crossed HTTP. Console answers what code reported. React DevTools answers which component owns props/state/hooks.' },
  ], [q('debug-1', 'If Network shows 200 but the name is blank, what should you inspect next?', ['Only CSS', 'Response shape and JSX property access', 'The database password first', 'Browser zoom'], 1, 'A successful response can still have a different property name or an unexpected nesting. Compare the payload with the JSX read.')], ['debugging', 'devtools'], { title: 'Investigate the blank name', prompt: 'Move through the simulated DevTools investigation and identify the first failed checkpoint.', hints: ['Start with the route and render checks.', 'Compare the response property with the JSX expression.'] }),
  lesson('production-flow', 5, 'Trace a production request', 'Connect browser UI, React architecture, HTTP, and Spring Boot layers in one flow.', [
    { title: 'The whole path', body: 'Browser → entry point → App → router → page → component → custom Hook → service → HTTP client → Spring controller → service → repository → database. Click a layer in the diagram to inspect its responsibility.', code: `Page\n  ↓\nuseCustomers()\n  ↓\ncustomerService.getCustomers()\n  ↓\nGET /api/customers` },
    { title: 'The payoff', body: 'When you can name the boundary where a value changes, production debugging becomes a traceable investigation instead of a search through every file.' },
  ], [q('flow-1', 'Which layer should translate an API response into React loading state?', ['The database', 'A React Hook or page lifecycle boundary', 'CSS', 'The URL bar'], 1, 'The Hook or page coordinates request state and exposes loading/error/data for the UI. The service should stay focused on communication.')], ['architecture', 'api', 'spring']),
  lesson('final-project', 5, 'Customer Management project', 'Explore a compact production-style app where every concept connects.', [
    { title: 'Follow one feature', body: 'Search begins as input state, flows into useCustomers, reaches the mock service, and returns a filtered list. Details use a route parameter. Mutations update the service and refresh the Hook.', code: `CustomerListPage\n  ↓\nuseCustomers()\n  ↓\ncustomerService\n  ↓\nmock API` },
    { title: 'Read it like a real repository', body: 'Use the project tabs to inspect the list, details, form, and architecture. The app models loading, errors, empty states, controlled inputs, routes, and service boundaries together.' },
  ], [q('final-1', 'Where should a customer search query be owned?', ['As an untracked DOM mutation', 'In the list page or a Hook that controls the list', 'Inside a CSS rule', 'Only in the database'], 1, 'The page or Hook owns the UI query, then sends it to the service/data flow that produces the visible list.')], ['project', 'crud', 'architecture'], { title: 'Ship one improvement', prompt: 'Use the project to add a customer, search for them, open details, edit them, and remove them.', hints: ['Observe each route change.', 'Use the architecture panel to connect the UI action to the mock service.'] }),
];

lessons.push(
  lesson('state-snapshots', 2, 'State snapshots', 'Understand why each render sees a fixed set of JavaScript values.', [
    { title: 'A render is a snapshot', body: 'When React calls a component, its props, state variables, and event handlers belong to that one execution. Calling a setter requests a future render; it does not rewrite the values already running in the current function.', code: `function Counter() {\n  const [count, setCount] = useState(0);\n  // this handler remembers this render's count\n  return <button onClick={() => setCount(count + 1)}>{count}</button>;\n}`, takeaway: 'A callback created in Render #1 can still remember Render #1 after Render #2 exists.' },
    { title: 'Why logs can surprise you', body: 'A console.log immediately after setCount still reads the current snapshot. The updated value becomes available when React runs the component again.' },
  ], [q('snapshot-1', 'When does a new state value become available to component code?', ['Immediately inside the same handler', 'On a later render scheduled by React', 'Only after a browser reload', 'Inside CSS'], 1, 'The current render is fixed. React stores the requested update and gives the new value to the next render.')], ['state', 'render', 'closures']),
  lesson('batching', 2, 'Batching and functional updates', 'See why several state updates can be grouped, and why updater functions compose reliably.', [
    { title: 'Batching groups work', body: 'React can process several updates from one event together and render once. Batching avoids intermediate work, but it does not make direct expressions read newer values.', code: `setCount(count + 1);\nsetCount(count + 1);\nsetCount(count + 1);` },
    { title: 'Updaters form a queue', body: 'A functional updater receives the latest queued value. Three c => c + 1 updates can therefore build 0 → 1 → 2 → 3 even though React still commits one final render.', code: `setCount(c => c + 1);\nsetCount(c => c + 1);\nsetCount(c => c + 1);`, takeaway: 'Use functional updates when the next value depends on the previous value.' },
  ], [q('batching-1', 'What makes three functional updates accumulate?', ['Each updater receives the latest queued value', 'The browser runs three page reloads', 'The setter mutates the old variable', 'CSS stores the count'], 0, 'React applies each updater to the result of the previous updater in the queue.')], ['state', 'batching', 'events']),
  lesson('state-preservation', 2, 'State preservation and reset', 'Predict when React keeps a component state slot and when a key creates a fresh identity.', [
    { title: 'Position and identity', body: 'React can preserve state when the same component type remains in the same tree position. A different key tells React that the rendered identity changed, so the old local state should not be reused.', code: `<ProfileEditor key={person.id} person={person} />` },
    { title: 'Reset intentionally', body: 'Keys are commonly introduced for list identity, but they can also reset a form when a route or selected record changes. This is an explicit identity decision, not a random refresh.', takeaway: 'Ask whether the new UI represents the same component instance or a new one.' },
  ], [q('preserve-1', 'What can intentionally reset local component state?', ['Changing the component key', 'Changing a CSS class', 'Reading a prop', 'Calling console.log'], 0, 'A new key changes component identity, so React creates a new state instance instead of preserving the previous one.')], ['state', 'keys', 'identity']),
  lesson('closures', 3, 'Closures and stale values', 'Connect JavaScript closures directly to React renders, timers, effects, and callbacks.', [
    { title: 'Each render creates a context', body: 'A component render creates new local bindings and new functions. A timer or effect callback can close over the values from the render that created it.', code: `const [count, setCount] = useState(0);\n\nsetTimeout(() => {\n  console.log(count);\n}, 1000);`, takeaway: 'The callback remembers a render snapshot, not a live mutable variable.' },
    { title: 'Choose the right fix', body: 'Dependencies tell an effect when a captured value must be refreshed. Functional updates avoid reading an old value when the next state depends on the previous state. These solve different problems.' },
  ], [q('closure-1', 'Why can a timer log an older count?', ['It captured the count from the render that created it', 'React changes CSS later', 'The database sends a count', 'Timers always reset state'], 0, 'JavaScript closures preserve access to the lexical environment from the render where the callback was created.')], ['javascript', 'closures', 'effects']),
);
lessons.sort((left, right) => left.day - right.day);

export const lessonsByDay = (day: DayNumber) => lessons.filter(item => item.day === day);
export const getLesson = (id?: string) => lessons.find(item => item.id === id) ?? lessons[0];
export const getNextLesson = (id: string) => {
  const index = lessons.findIndex(item => item.id === id);
  return lessons[(index + 1) % lessons.length];
};
