interface LensContent {
  oneSentence: string;
  mentalModel: string;
  inspect: string[];
  production: string;
  question: string;
}

const defaultLens: LensContent = {
  oneSentence: 'React turns JavaScript values into a UI description, then keeps that description synchronized with the browser.',
  mentalModel: 'Read the feature as a chain: input → JavaScript → React state → render → committed UI.',
  inspect: ['What value starts the chain?', 'Which component owns it?', 'What event or effect can change it?'],
  production: 'Look for the component that composes the screen, then trace its props, Hooks, and service calls in that order.',
  question: 'What is the next observable step after this code runs?',
};

const lenses: Record<string, LensContent> = {
  'javascript-foundations': { oneSentence: 'React code is JavaScript that produces descriptions of UI.', mentalModel: 'Objects hold data, functions transform it, and expressions can be evaluated while a component renders.', inspect: ['Where is data shaped?', 'Is map creating a new collection?', 'Where does async work resume?'], production: 'Start with the data transformation before reading JSX. The UI often reveals the shape returned by a service.', question: 'Which JavaScript expression produces the value this UI displays?' },
  jsx: { oneSentence: 'JSX is syntax for describing an element tree from current JavaScript values.', mentalModel: 'JSX braces are the boundary where JavaScript values enter the UI description.', inspect: ['Which expressions are evaluated?', 'What tree does the return value describe?', 'Which values will change on the next render?'], production: 'When JSX looks wrong, inspect the values and branches that produce it before changing CSS.', question: 'What element description will this expression produce right now?' },
  components: { oneSentence: 'A component is a function React executes to calculate one UI responsibility.', mentalModel: 'Component function → JSX description → React compares → browser receives necessary DOM changes.', inspect: ['Who renders this component?', 'What inputs does it read?', 'Does it cause side effects during render?'], production: 'Use component boundaries to decide where to look for ownership, not as a promise that each component maps to one DOM node.', question: 'Which component function runs when this part of the screen needs new UI?' },
  props: { oneSentence: 'Props are read-only inputs a parent gives a child for a particular render.', mentalModel: 'Parent owns the value; child receives a snapshot and reports events back through callbacks.', inspect: ['Where is the prop created?', 'Does the child only read it?', 'Which callback communicates an event upward?'], production: 'Follow the prop at the call site first. That is usually where the real owner and next update live.', question: 'If the parent value changes, which child input changes next?' },
  rendering: { oneSentence: 'A re-render runs component JavaScript again; it is not a browser reload.', mentalModel: 'Trigger → component execution → JSX calculation → comparison → only necessary commit.', inspect: ['What triggered this render?', 'Did the DOM actually change?', 'Which component function executed?'], production: 'Use render logs and React DevTools to separate component execution from visible DOM work.', question: 'What runs again, and what can remain unchanged?' },
  'entry-point': { oneSentence: 'The entry point gives React ownership of one browser DOM node.', mentalModel: 'Browser HTML provides #root; createRoot attaches React; the rendered tree starts there.', inspect: ['Which element is the root?', 'What Provider and Router wrap the app?', 'Where does the first component enter?'], production: 'Start at main.tsx or main.jsx when you need to understand providers, routing, and application-wide setup.', question: 'Which DOM node is React allowed to manage?' },
  'use-state': { oneSentence: 'useState gives a component memory that survives its function being called again.', mentalModel: 'The initializer creates a state slot once; the setter requests a future render with a new value.', inspect: ['What is the current render snapshot?', 'Which setter schedules the update?', 'Is the initial argument being mistaken for a reset?'], production: 'Find the setter to learn what events can change a screen, then find every reader of that state.', question: 'What value will the next render read from React memory?' },
  events: { oneSentence: 'An event handler is the bridge from a browser action to a React state update.', mentalModel: 'Browser event → handler → setter → scheduled render → new JSX → committed UI.', inspect: ['Which handler is registered?', 'What values did its render snapshot capture?', 'Which setter did it call?'], production: 'Trace from the JSX handler prop, not from the final visual change.', question: 'What exact state update does this event request?' },
  'conditional-rendering': { oneSentence: 'Conditional rendering chooses a different UI description from current state.', mentalModel: 'State describes the situation; a branch describes the UI for that situation.', inspect: ['Which branch is active?', 'What state controls it?', 'Are loading, empty, error, and success distinct?'], production: 'Treat each branch as a state contract rather than hiding missing data with a generic fallback.', question: 'Which branch should React return for this state?' },
  'lists-and-keys': { oneSentence: 'Keys tell React which list item is the same logical item across renders.', mentalModel: 'Data identity is not position. Stable IDs let component state stay with the right item.', inspect: ['Can items reorder or be inserted?', 'Is the key stable?', 'Does the row contain local state?'], production: 'Inspect the domain model for a stable ID before reaching for an array index.', question: 'Which row should React preserve after this list change?' },
  forms: { oneSentence: 'A controlled input keeps the browser field synchronized with React state.', mentalModel: 'Keystroke → onChange → state → render → value prop back to the input.', inspect: ['Who owns the value?', 'Is there an update path?', 'Does submit prevent navigation?'], production: 'Read the value and onChange together; separating them often reveals a controlled form bug.', question: 'Where will the typed character be stored before it appears again?' },
  'state-ownership': { oneSentence: 'Shared state belongs in the closest common owner of the components that need it.', mentalModel: 'One owner → explicit data down → callbacks up → siblings stay synchronized.', inspect: ['Who needs the value?', 'What is the closest common parent?', 'Are updates immutable?'], production: 'If two controls disagree, find whether they are reading separate copies instead of one owner.', question: 'Which component can see and update every consumer without duplication?' },
  effects: { oneSentence: 'An effect synchronizes React with an external system after the UI commits.', mentalModel: 'Trigger → render → commit → effect setup; dependency change or unmount can run cleanup first.', inspect: ['What external system is synchronized?', 'Which render values are read?', 'What cleanup stops old work?'], production: 'Name the external system before writing an effect. If there is none, the logic may belong in render or an event.', question: 'Why is this work allowed after commit instead of during render?' },
  'dependency-arrays': { oneSentence: 'A dependency array tells React which values can make an effect setup obsolete.', mentalModel: 'Previous values vs current values → unchanged skips; changed cleans up old work and runs new work.', inspect: ['What values are read?', 'Which value changed?', 'Could an old closure continue running?'], production: 'Compare the dependency list with values referenced inside the effect, then inspect cleanup.', question: 'Which comparison decides whether the effect runs?' },
  'promises-and-async': { oneSentence: 'A Promise represents work whose result will be fulfilled or rejected later.', mentalModel: 'Start → pending → await resumes on fulfillment or jumps to catch on rejection.', inspect: ['Where does pending become visible?', 'Where is rejection handled?', 'Which state update follows settlement?'], production: 'Keep the async boundary visible in loading/error state instead of assuming the happy path.', question: 'What can the user see while this Promise is pending?' },
  'api-flow': { oneSentence: 'An API feature is a sequence of renders and asynchronous state transitions, not one request line.', mentalModel: 'Initial render → commit → effect → pending → response → state update → second render.', inspect: ['What does the first render show?', 'Where does the request begin?', 'Which response field does JSX read?'], production: 'Trace route, render, Network, response shape, setter, re-render, and JSX in that order.', question: 'Which state makes loading, error, empty, or success visible now?' },
  'custom-hooks': { oneSentence: 'A custom Hook packages reusable React stateful behavior without owning a visual layout.', mentalModel: 'Page composes UI; Hook coordinates state/effects; service owns HTTP details.', inspect: ['What state does the Hook expose?', 'What starts its effect?', 'Where does the service boundary begin?'], production: 'Follow Component → Hook → Service before reading backend details.', question: 'Which responsibility belongs in the Hook rather than the service?' },
  context: { oneSentence: 'Context supplies a shared value to distant descendants without threading every intermediate prop.', mentalModel: 'Provider establishes a value; consumers subscribe to that value at their tree position.', inspect: ['Who provides the value?', 'Which consumers read it?', 'Is this truly shared or merely convenient?'], production: 'Use Context for stable app-wide concerns; keep feature-local state near its owner.', question: 'Which consumers should update when the Provider value changes?' },
  refs: { oneSentence: 'A ref stores a mutable value or DOM handle without scheduling a render.', mentalModel: 'React renders declaratively; an event can use ref.current for one imperative interaction.', inspect: ['Does the value need to appear in UI?', 'When is current available?', 'Could focus or measurement be the real need?'], production: 'If changing it should update pixels, it is probably state, not a ref.', question: 'What can change without React recalculating JSX?' },
  memoization: { oneSentence: 'Memoization is an optimization that reuses work or identity when dependencies are unchanged.', mentalModel: 'Measure a costly boundary → cache it → invalidate when relevant input changes.', inspect: ['What work is expensive?', 'Which dependency invalidates it?', 'Does a child actually compare identity?'], production: 'Look for a measured bottleneck or memoized boundary before adding useMemo or useCallback.', question: 'What work is being avoided, and what proves it matters?' },
  'rules-of-hooks': { oneSentence: 'Stable Hook call order lets React match state and effects with the right component instance.', mentalModel: 'Top-level Hook call #1 remains Hook call #1 on every render.', inspect: ['Are Hooks top-level?', 'Could a condition change call order?', 'Can the condition wrap returned UI instead?'], production: 'Lint rules are a useful map of lifecycle assumptions, not stylistic noise.', question: 'Will this Hook call have the same position on the next render?' },
  routing: { oneSentence: 'Routing maps a URL contract to a page component and its parameters.', mentalModel: 'URL → route match → page → params → data request → rendered screen.', inspect: ['Which route pattern matches?', 'What params are extracted?', 'Does direct refresh have a server fallback?'], production: 'A route is a public contract shared by links, browser history, APIs, and deployment config.', question: 'Which page and resource identity does this URL select?' },
  'repository-structure': { oneSentence: 'A React repository is easiest to read by tracing a feature across explicit boundaries.', mentalModel: 'Entry point → router → page → components/Hook → service → API.', inspect: ['Where is composition?', 'Where is lifecycle state?', 'Where does HTTP begin?'], production: 'This is the frontend parallel to tracing Controller → Service → Repository in Spring.', question: 'Which file owns the next responsibility in the data path?' },
  debugging: { oneSentence: 'Good debugging follows the execution chain instead of guessing from the final visual symptom.', mentalModel: 'Route → render → request → response → state update → re-render → JSX → DOM.', inspect: ['Which checkpoint was last proven?', 'What panel can prove the next one?', 'Is the response shape what JSX reads?'], production: 'Elements, Network, Console, and React DevTools each prove a different part of the trace.', question: 'What is the first unproven checkpoint?' },
  'production-flow': { oneSentence: 'A production feature is a chain of boundaries where data and responsibility change hands.', mentalModel: 'Browser → React → Hook → service → HTTP → Spring Boot → database → response back up.', inspect: ['Where does the request originate?', 'Where is loading owned?', 'Where does data become UI?'], production: 'Name the boundary where a value changes to narrow unfamiliar code quickly.', question: 'Which layer should own this concern?' },
  'final-project': { oneSentence: 'The Customer Management lab connects routing, forms, Hooks, services, and async UI into one traceable feature.', mentalModel: 'Input state → Hook → mock API → state update → re-render → visible customer list.', inspect: ['Who owns search/form state?', 'Which service operation ran?', 'What branch handles loading or empty?'], production: 'Use the architecture panel as a map, then inspect the corresponding page, Hook, and service files.', question: 'What code path runs after this customer action?' },
  'state-snapshots': { oneSentence: 'Each render sees a fixed snapshot of state; setters schedule a later render rather than changing that snapshot.', mentalModel: 'Render #1 has its own values and callbacks; Render #2 receives a new snapshot after React processes updates.', inspect: ['Which render created this handler?', 'How many queued updates read the same value?', 'Would a functional updater compose them?'], production: 'Stale event handlers and surprising logs usually make sense once you label their render snapshot.', question: 'Which snapshot does this callback remember?' },
  batching: { oneSentence: 'Batching groups updates so React can process them together, while updater functions compose from the latest queued value.', mentalModel: 'Direct values can collapse to the same next state; updater functions form a queue.', inspect: ['What value did each expression read?', 'What is in the update queue?', 'What value does each updater receive?'], production: 'Use functional updates whenever several updates may build on one another.', question: 'What value reaches the next render after the queue is processed?' },
  closures: { oneSentence: 'A callback created during a render closes over that render’s values, even after a newer render exists.', mentalModel: 'Render #1 creates callback #1 with count 0; Render #2 creates callback #2 with count 1.', inspect: ['When was the callback created?', 'Which values did it capture?', 'Should dependencies or a functional update change the design?'], production: 'Timers, effects, subscriptions, and callbacks are the usual places stale closures appear.', question: 'Which render does this function remember?' },
  'state-preservation': { oneSentence: 'React preserves state when the same component stays in the same tree position, and resets it when identity or position changes.', mentalModel: 'Type + position + key determine which state memory a rendered component can reuse.', inspect: ['Is the component type the same?', 'Did its position or key change?', 'Is reset intentional?'], production: 'Keys are not only for lists; they can deliberately reset a form or preserve a tab’s state.', question: 'Should React treat this as the same component instance?' },
};

export function LearningLens({ lessonId }: { lessonId: string }) {
  const lens = lenses[lessonId] ?? defaultLens;
  return <section className="learning-lens" aria-label="Learning lens">
    <div className="lens-lead"><span className="eyebrow accent">MENTAL MODEL</span><h2>{lens.oneSentence}</h2><p>{lens.mentalModel}</p></div>
    <div className="lens-grid"><div><span className="lens-label">READ THE CODE</span><ul>{lens.inspect.map(item => <li key={item}>{item}</li>)}</ul></div><div><span className="lens-label">WHERE THIS APPEARS</span><p>{lens.production}</p><div className="lens-question"><span>BEFORE YOU RUN IT</span><strong>{lens.question}</strong></div></div></div>
  </section>;
}
