import { createContext, useContext, useEffect, useMemo, useRef, useState } from 'react';
import { CodePanel } from './CodePanel';
import { ExecutionTimeline } from './ExecutionTimeline';
import { FlowDiagram, StatusPill } from './FlowDiagram';
import type { DemoEvent } from '../types';

const apiEvents: DemoEvent[] = [
  { id: 'open', label: 'CustomerPage starts', description: 'React begins the first render of the page.', codeLine: 1, stateSnapshot: 'customer: null' },
  { id: 'state', label: 'useState returns null', description: 'The initial UI has no customer data yet.', codeLine: 2, stateSnapshot: 'customer: null' },
  { id: 'commit', label: 'Loading is committed', description: 'React commits the first UI. The browser displays Loading…', stateSnapshot: 'UI: Loading…' },
  { id: 'effect', label: 'useEffect runs', description: 'The effect starts after commit, not during the render calculation.', codeLine: 4 },
  { id: 'request', label: 'HTTP request is pending', description: 'The service asks the mock Spring API for customer 101.', codeLine: 5, stateSnapshot: 'request: pending' },
  { id: 'response', label: 'JSON response arrives', description: 'The Promise fulfills with { id: 101, name: Harish Kumar }.', stateSnapshot: 'response: fulfilled' },
  { id: 'update', label: 'setCustomer(data)', description: 'React stores the response and schedules the next render.', codeLine: 7, stateSnapshot: 'customer: Harish Kumar' },
  { id: 'rerender', label: 'CustomerPage runs again', description: 'The component reads existing state, calculates new JSX, and React updates the name.', stateSnapshot: 'UI: Harish Kumar' },
];

export function CounterDemo() {
  const [count, setCount] = useState(0); const [renders, setRenders] = useState(1);
  const update = (next: number | ((value: number) => number)) => { setCount(next); setRenders(value => value + 1); };
  return <div className="demo-card"><div className="demo-header"><div><span className="eyebrow">LIVE REACT DEMO</span><h3>React State Memory</h3></div><StatusPill tone="success">actual useState</StatusPill></div><div className="state-grid"><div className="state-value"><span>count</span><strong>{count}</strong></div><div className="state-value"><span>render count</span><strong>{renders}</strong></div></div><div className="demo-actions"><button className="button primary" onClick={() => update(value => value + 1)}>+1</button><button className="button subtle" onClick={() => update(value => value - 1)}>-1</button><button className="button subtle" onClick={() => update(0)}>Reset</button></div><div className="event-strip"><span>setCount()</span><span>→</span><span>state memory</span><span>→</span><span>re-render</span></div></div>;
}

export function PropsDemo() { const [name, setName] = useState('Harish'); const [role, setRole] = useState('React learner'); return <div className="demo-card"><div className="demo-header"><div><span className="eyebrow">PARENT → CHILD</span><h3>Props are inputs</h3></div><StatusPill tone="warning">read-only in child</StatusPill></div><div className="props-controls"><label>Name<input value={name} onChange={event => setName(event.target.value)} /></label><label>Role<input value={role} onChange={event => setRole(event.target.value)} /></label></div><div className="prop-flow"><div className="prop-node"><span>Parent</span><code>&lt;User name="{name}" /&gt;</code></div><span>↓ props</span><div className="prop-node highlighted"><span>Child: User</span><strong>{name}</strong><small>{role}</small></div></div></div>; }

export function JsxDemo() { const [name, setName] = useState('Harish'); return <div className="demo-card"><div className="demo-header"><div><span className="eyebrow">EDIT + PREVIEW</span><h3>Curly braces evaluate JavaScript</h3></div></div><div className="split-demo"><div><label className="field-label">const name</label><input className="large-input" value={name} onChange={event => setName(event.target.value)} /></div><div className="live-preview"><span>Live UI</span><h2>Hello {name || 'learner'}</h2><small>{'<h2>Hello {name}</h2>'}</small></div></div></div>; }

export function FormDemo() { const [name, setName] = useState(''); const [submitted, setSubmitted] = useState(''); return <div className="demo-card"><div className="demo-header"><div><span className="eyebrow">CONTROLLED INPUT</span><h3>Keyboard → state → UI</h3></div></div><form className="form-demo" onSubmit={event => { event.preventDefault(); setSubmitted(name); }}><input value={name} onChange={event => setName(event.target.value)} placeholder="Type a customer name" /><button className="button primary">Save name</button></form><div className="form-status">state.name = <strong>{name || '""'}</strong>{submitted && <span> · submitted: {submitted}</span>}</div></div>; }

export function ListDemo() { const [users, setUsers] = useState(['Asha', 'Maya']); const [next, setNext] = useState(1); return <div className="demo-card"><div className="demo-header"><div><span className="eyebrow">STABLE IDENTITY</span><h3>Keys help React match items</h3></div><button className="button subtle" onClick={() => { setUsers(items => [...items, `New user ${next}`]); setNext(value => value + 1); }}>+ Add user</button></div><div className="list-demo">{users.map((user, index) => <div className="list-row" key={user}><span className="drag-grip">⠿</span><strong>{user}</strong><code>key="{user}"</code><button className="icon-button" aria-label={`Remove ${user}`} onClick={() => setUsers(items => items.filter(item => item !== user))}>×</button><small>position {index}</small></div>)}</div><p className="muted">Try removing the first item. The key stays attached to the logical user, not its position.</p></div>; }

export function ApiDemo() { const [mode, setMode] = useState<'success' | 'error' | 'empty' | 'slow'>('success'); const [running, setRunning] = useState(false); const [result, setResult] = useState(''); const run = () => { setRunning(true); setResult('Loading…'); window.setTimeout(() => { setRunning(false); setResult(mode === 'success' ? 'Harish Kumar' : mode === 'empty' ? 'No customers found' : mode === 'error' ? 'Request failed · 500' : 'Slow API · response received'); }, mode === 'slow' ? 1600 : 650); }; return <div className="demo-card api-demo"><div className="demo-header"><div><span className="eyebrow">MOCK API SIMULATOR</span><h3>Loading / success / error / empty</h3></div><StatusPill tone={result.includes('failed') ? 'danger' : result === 'Loading…' ? 'warning' : 'success'}>{running ? 'pending' : 'ready'}</StatusPill></div><div className="api-mode-buttons">{(['success', 'error', 'empty', 'slow'] as const).map(item => <button key={item} className={`mode-button ${mode === item ? 'active' : ''}`} onClick={() => { setMode(item); setResult(''); }}>{item}</button>)}</div><div className="api-result"><span>GET /api/customers/101</span><strong>{result || 'Press Run to start the request'}</strong></div><button className="button primary" onClick={run} disabled={running}>{running ? 'Request in flight…' : 'Run request'}</button></div>; }

export function ApiTimeline() { const [activeLine, setActiveLine] = useState<number>(); const apiCode = `function CustomerPage() {\n  const [customer, setCustomer] = useState(null);\n  useEffect(() => {\n    fetch('/api/customers/101')\n      .then(response => response.json())\n      .then(data => setCustomer(data));\n  }, []);\n}`; return <><ExecutionTimeline events={apiEvents} onActiveChange={event => setActiveLine(event.codeLine)} /><CodePanel code={apiCode} title="CustomerPage.jsx" activeLine={activeLine} /><div className="code-sync-note"><span className="pulse-dot" />The highlighted line is the source of the active execution step.</div></>; }

export function RefDemo() { const input = useRef<HTMLInputElement>(null); return <div className="demo-card"><div className="demo-header"><div><span className="eyebrow">IMPERATIVE HANDLE</span><h3>Focus a DOM element with useRef</h3></div></div><div className="ref-demo"><input ref={input} placeholder="The ref points here" /><button className="button primary" onClick={() => input.current?.focus()}>inputRef.current.focus()</button></div><p className="muted">The ref gives the handler a DOM node. Updating it does not schedule a re-render.</p></div>; }

export function MemoDemo() { const [query, setQuery] = useState(''); const [renders, setRenders] = useState(0); const calculationCount = useRef(0); const result = useMemo(() => { calculationCount.current += 1; return query.trim().length * 42; }, [query]); return <div className="demo-card"><div className="demo-header"><div><span className="eyebrow">MEASURE BEFORE OPTIMIZING</span><h3>Calculation and render identity</h3></div><button className="button subtle" onClick={() => setRenders(value => value + 1)}>Parent re-render</button></div><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Change the dependency" /><div className="memo-stats"><div><span>derived value</span><strong>{result}</strong></div><div><span>parent renders</span><strong>{renders}</strong></div><div><span>calculation runs</span><strong>{calculationCount.current}</strong></div></div><p className="muted">useMemo can cache the derived result while query is unchanged; it should be introduced when the work or identity boundary justifies it.</p></div>; }

export function ArchitectureDemo() { const [active, setActive] = useState(0); const steps = ['Browser', 'React entry point', 'Router', 'Page', 'Custom Hook', 'Service', 'HTTP client', 'Spring Boot controller', 'Database']; const descriptions = ['The user sees pixels and interacts.', 'createRoot attaches React to #root.', 'The URL selects a page.', 'The page composes UI and owns screen state.', 'React lifecycle and data state live here.', 'HTTP details are centralized here.', 'Requests cross the network boundary.', 'The backend receives the request.', 'Persistent data lives here.']; return <div className="demo-card"><div className="demo-header"><div><span className="eyebrow">PRODUCTION TRACE</span><h3>Click a layer in the request path</h3></div></div><FlowDiagram steps={steps} active={active} onSelect={setActive} /><div className="architecture-detail"><strong>{steps[active]}</strong><p>{descriptions[active]}</p></div></div>; }

export function StateMemoryDemo() { const [customer, setCustomer] = useState<string | null>(null); const [render, setRender] = useState(1); const load = () => { setCustomer('Harish'); setRender(value => value + 1); }; return <div className="demo-card"><div className="demo-header"><div><span className="eyebrow">REACT MEMORY</span><h3>Initial value is not a reset value</h3></div><StatusPill tone="success">real useState</StatusPill></div><div className="memory-grid"><div className="memory-step"><span>RENDER #{render}</span><strong>CustomerPage()</strong><code>useState(null)</code><small>{render === 1 ? 'React creates the state slot.' : 'React retrieves the existing slot.'}</small></div><div className="memory-value"><span>React state memory</span><strong>{customer ?? 'customer: null'}</strong><small>{customer ? 'setCustomer(data) stored the response.' : 'Initial state before the request.'}</small></div></div><button className="button primary" onClick={load}>{customer ? 'Run again' : 'setCustomer({ name: "Harish" })'}</button><div className="event-strip"><span>state slot</span><span>→</span><span>setter</span><span>→</span><span>next render</span><span>→</span><span>existing value</span></div></div>; }

export function RenderFlowDemo() { const [render, setRender] = useState(1); const events: DemoEvent[] = [{ id: 'component', label: 'Component executes', description: 'React calls the function to calculate the UI.', stateSnapshot: `render #${render}` }, { id: 'jsx', label: 'JSX is calculated', description: 'The return value describes the UI for this state.' }, { id: 'changes', label: 'React determines changes', description: 'React compares the new description with the previous one.' }, { id: 'dom', label: 'DOM is updated', description: 'The browser receives only the necessary DOM changes.' }]; return <div className="demo-card"><div className="demo-header"><div><span className="eyebrow">RENDER → COMMIT</span><h3>Rendering is not a page reload</h3></div><button className="button primary" onClick={() => setRender(value => value + 1)}>Trigger re-render</button></div><div className="render-count">Render count <strong>{render}</strong></div><ExecutionTimeline events={events} /></div>; }

export function EventFlowDemo() { const [count, setCount] = useState(0); return <div className="demo-card"><div className="demo-header"><div><span className="eyebrow">EVENT TRACE</span><h3>Click → handler → state → UI</h3></div><button className="button primary" onClick={() => setCount(value => value + 1)}>Click me ({count})</button></div><FlowDiagram steps={['click', 'event handler', 'setCount()', 're-render', `UI count = ${count}`]} active={4} /><p className="muted">The last node changes only because the handler called the setter.</p></div>; }

export function ParentChildDemo() { const [parentCount, setParentCount] = useState(0); const [childValue, setChildValue] = useState('Asha'); return <div className="demo-card"><div className="demo-header"><div><span className="eyebrow">PARENT / CHILD RENDERING</span><h3>Parent updates can re-evaluate children</h3></div><button className="button subtle" onClick={() => setParentCount(value => value + 1)}>Update parent</button></div><div className="parent-child-grid"><div className="prop-node"><span>Parent render #{parentCount + 1}</span><button className="button subtle" onClick={() => setChildValue(value => value === 'Asha' ? 'Maya' : 'Asha')}>Change child prop</button><code>name="{childValue}"</code></div><div className="prop-node highlighted"><span>Child receives prop</span><strong>{childValue}</strong><small>new JSX is calculated here</small></div></div><div className="event-strip"><span>parent state</span><span>→</span><span>parent executes</span><span>→</span><span>child receives props</span></div></div>; }

export function EffectLifecycleDemo() { const [tick, setTick] = useState(0); const [effectRuns, setEffectRuns] = useState(0); useEffect(() => { setEffectRuns(value => value + 1); }, [tick]); return <div className="demo-card"><div className="demo-header"><div><span className="eyebrow">AFTER COMMIT</span><h3>Effects run after the UI commits</h3></div><button className="button primary" onClick={() => setTick(value => value + 1)}>Render again</button></div><FlowDiagram steps={[`render (tick ${tick})`, 'commit UI', 'useEffect runs', `effect runs: ${effectRuns}`]} active={3} /><p className="muted">The effect reads tick after React commits. In development Strict Mode, initial setup may be replayed intentionally.</p></div>; }

export function DependencyDemo() { const [userId, setUserId] = useState(101); const [runs, setRuns] = useState(0); useEffect(() => { setRuns(value => value + 1); }, [userId]); return <div className="demo-card"><div className="demo-header"><div><span className="eyebrow">DEPENDENCY ARRAY</span><h3>Only changed dependencies rerun the effect</h3></div><div className="demo-actions"><button className="button subtle" onClick={() => setUserId(101)}>userId 101</button><button className="button primary" onClick={() => setUserId(102)}>userId 102</button></div></div><div className="dependency-state"><div><span>current dependency</span><strong>userId = {userId}</strong></div><div><span>effect executions</span><strong>{runs}</strong></div></div><FlowDiagram steps={['render', `compare [${userId}]`, userId === 102 ? 'dependency changed → effect' : 'dependency unchanged → skip']} active={2} /></div>; }

export function PromiseDemo() { const [status, setStatus] = useState('idle'); const run = (outcome: 'success' | 'error') => { setStatus('pending'); new Promise<string>((resolve, reject) => window.setTimeout(() => outcome === 'success' ? resolve('customer data') : reject(new Error('request failed')), 500)).then(value => setStatus(`fulfilled → ${value}`)).catch(() => setStatus('rejected → catch error')); }; return <div className="demo-card"><div className="demo-header"><div><span className="eyebrow">PROMISE STATE MACHINE</span><h3>Pending becomes fulfilled or rejected</h3></div><div className="demo-actions"><button className="button primary" onClick={() => run('success')}>Resolve</button><button className="button subtle" onClick={() => run('error')}>Reject</button></div></div><div className={`promise-state ${status}`}><span>Promise state</span><strong>{status}</strong></div><FlowDiagram steps={['pending', 'fulfilled', 'rejected']} active={status.startsWith('fulfilled') ? 1 : status.startsWith('rejected') ? 2 : 0} /><p className="muted">fetch returns the Promise immediately. React state makes the settled result visible in the UI.</p></div>; }

function useDemoUsers() { const [version, setVersion] = useState(0); const [users, setUsers] = useState<string[]>([]); useEffect(() => { const timer = window.setTimeout(() => setUsers(['Asha', 'Maya', 'Harish']), 350); return () => window.clearTimeout(timer); }, [version]); return { users, loading: users.length === 0, refresh: () => { setUsers([]); setVersion(value => value + 1); } }; }
export function HookFlowDemo() { const { users, loading, refresh } = useDemoUsers(); return <div className="demo-card"><div className="demo-header"><div><span className="eyebrow">CUSTOM HOOK</span><h3>Page consumes reusable lifecycle logic</h3></div><button className="button subtle" onClick={refresh}>Run useUsers()</button></div><FlowDiagram steps={['UsersPage', 'useUsers()', 'useState + useEffect', 'service', 'API']} active={loading ? 2 : 4} /><div className="hook-output">{loading ? 'Loading users…' : users.join(' · ')}</div></div>; }

const DemoContext = createContext('guest');
function ContextConsumer() { const role = useContext(DemoContext); return <div className="context-consumer"><span>Consumer reads AuthContext</span><strong>{role}</strong></div>; }
export function ContextDemo() { const [role, setRole] = useState('guest'); return <div className="demo-card"><div className="demo-header"><div><span className="eyebrow">PROVIDER → TREE → CONSUMER</span><h3>Context skips unrelated prop passing</h3></div><button className="button primary" onClick={() => setRole(value => value === 'guest' ? 'Harish · signed in' : 'guest')}>Change provider value</button></div><FlowDiagram steps={['AuthProvider', 'App tree', 'CustomerPage', 'useContext(AuthContext)']} active={3} /><DemoContext.Provider value={role}><ContextConsumer /></DemoContext.Provider></div>; }

export function HookRulesDemo() { const [showBad, setShowBad] = useState(false); return <div className="demo-card"><div className="demo-header"><div><span className="eyebrow">HOOK ORDER</span><h3>Keep Hook calls at the top level</h3></div><button className="button subtle" onClick={() => setShowBad(value => !value)}>{showBad ? 'Show good example' : 'Show bad example'}</button></div><CodePanel code={showBad ? `if (loggedIn) {\n  useState(null);\n}` : `function Component() {\n  const [count, setCount] = useState(0);\n  return <button>{count}</button>;\n}`} /><p className="muted">React matches state slots by call order. Conditions belong around returned UI, not around Hook calls.</p></div>; }
